### ISSUE TITLE
Issue installing the library

### ISSUE THREAD

**Issue by nathjwhite** [lemberg/obd2-swift-lib#8]
After cloning the repository, there is no OBD2Swift.xcodeproj in the OBD2-Swift folder. 

How can I manually install the library?

**Comment by OverSwift** [comment]
Hi check is today. in OBD2-Swift folder contains only library classes. To try the library you can run example project in Example folder. Also library can be installed via cocoa pods, just add `pod 'OBD2-Swift'` to your pod file and add import OBD2

**Comment by nathjwhite** [comment]
Great! I was following the instructions in the README, but the cocoa pods method is exactly what I was looking for.
