### ISSUE TITLE
Exception with demo app after AT DP\r

### ISSUE THREAD

**Issue by tropicdome** [lemberg/obd2-swift-lib#9]
First of all, great work with the library!

I tried out the demo app, and when I press connect, it crashes after some time. The output from the the console says it connects and communicates, see debug output below:

```
Input stream opened
Output stream opened
isFinished true
isExecuting false
isFinished true
open operation completed without errors
Write to OBD Optional("AT WS\r")
Wrote 6 bytes
Read 16 bytes
Read complete


ELM327 v2.1
Write to OBD Optional("AT E0\r")
Wrote 6 bytes
Read 11 bytes
Read complete
AT E0
OK
Write to OBD Optional("AT I\r")
Wrote 5 bytes
Read 14 bytes
Read complete
ELM327 v2.1
Write to OBD Optional("01 00\r")
Wrote 6 bytes
Read 10 bytes
Read 1 bytes
Read 1 bytes
Read 1 bytes
Read 22 bytes
Read 2 bytes
Read complete
BUS INIT: ...OK
41 00 BE 3E B8 11 
Set new pid group 0
Set new pid group 0
Write to OBD Optional("AT DP\r")
Wrote 6 bytes
Read 13 bytes
Read complete
ISO 9141-2
(lldb) 
```

The breakpoint jumps to InitScanerOperation.swift:157 as shown in the screenshot below.

<img width="1110" alt="screenshot" src="https://user-images.githubusercontent.com/1110907/32134116-4280cd2a-bbe6-11e7-96b2-01416b8897c5.png">

Do you have any idea why it crashes? The debugger does not give much information.

/cheers

**Comment by MaxVitruk** [comment]
Hello @tropicdome ! Thanks for feedback !. Could you please tell more about hardware which you are using to connect with OBD2 interface ? Seems like index out of bound.

**Comment by tropicdome** [comment]
I use the Vgate iCar2 ELM327 Wifi OBD2. I try to connect using my iPhone 6s and also iPad 4.

**Comment by mustundag** [comment]
Hello,

I solved this problem in my environment.

I changed 
   ...
   self.init(host : "127.0.0.1", port : 35000)
   ...
in OBD2Facade.swift at line 32.

Because I am using OBD2Simulator from App Store. And it is using 127.0.0.1 host.

Regards

**Comment by tropicdome** [comment]
Thanks for the answer, but why should I change it to localhost when I need to connect to the ELM327 device? As I posted above, it actually connects and communicates, however, during that process it crashes 😕

**Comment by OverSwift** [comment]
Hi @tropicdome , check issue today and fix it. Also new version is available via cocoa pods

**Comment by tropicdome** [comment]
Awesome, will check it out tonight. Thanks, keep up the good work!

**Comment by tropicdome** [comment]
Just tested, it works, thank you very much! :)

A different question. Why did you update the podspec to min. iOS 9.3 instead of 9.0?
